// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owpohlvhjvgchfqnjvxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93cG9obHZoanZnY2hmcW5qdnhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDM2MTksImV4cCI6MjA3MDc3OTYxOX0.E5J23rWfVW7YTprykltlHQAjznnGqD3ixxKOi_3mQZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});